import { z } from "zod";
import type { PaClient } from "../client.js";

const OrderFields = {
  organization_id: z.number().describe("ID of the organization this scheduled order belongs to"),
  description: z.string().optional().describe("Internal description / label for this order"),
  active: z.boolean().optional().describe("Whether this scheduled order is currently active"),
  distribution: z
    .enum(["standard", "premium"])
    .optional()
    .describe("Distribution tier for releases generated by this order"),
  order_type: z.string().optional().describe("Type of order (e.g. 'written_for_you' or 'self_written')"),
  schedule_days: z.number().optional().describe("How many days between each scheduled release"),
  keywords_per_release: z.number().optional().describe("Number of keywords to include per release"),
};

export function scheduledOrderTools({ paGet, paPost, paPut }: PaClient) {
  return [
    {
      name: "list_scheduled_orders",
      description: "List all scheduled release orders in the account",
      inputSchema: z.object({}),
      handler: async () => paGet("/scheduled_release_orders.json"),
    },
    {
      name: "get_scheduled_order",
      description: "Get details of a single scheduled release order",
      inputSchema: z.object({
        id: z.number().describe("Scheduled release order ID"),
      }),
      handler: async ({ id }: { id: number }) =>
        paGet(`/scheduled_release_orders/${id}.json`),
    },
    {
      name: "create_scheduled_order",
      description:
        "Create a new scheduled release order that automatically generates recurring press releases",
      inputSchema: z.object(OrderFields),
      handler: async (input: Record<string, unknown>) =>
        paPost("/scheduled_release_orders.json", { scheduled_release_order: input }),
    },
    {
      name: "update_scheduled_order",
      description: "Update an existing scheduled release order",
      inputSchema: z.object({
        id: z.number().describe("Scheduled release order ID to update"),
        ...Object.fromEntries(
          Object.entries(OrderFields).map(([k, v]) => [k, v.optional()])
        ),
      }),
      handler: async ({ id, ...rest }: { id: number } & Record<string, unknown>) =>
        paPut(`/scheduled_release_orders/${id}.json`, { scheduled_release_order: rest }),
    },
    {
      name: "add_scheduled_video",
      description: "Attach a video to a scheduled release order",
      inputSchema: z.object({
        scheduled_order_id: z.number().describe("Scheduled release order ID"),
        url: z.string().describe("Video URL"),
        title: z.string().optional().describe("Video title"),
      }),
      handler: async ({ scheduled_order_id, ...rest }: { scheduled_order_id: number } & Record<string, unknown>) =>
        paPost(`/scheduled_release_orders/${scheduled_order_id}/scheduled_release_video.json`, {
          scheduled_release_video: rest,
        }),
    },
    {
      name: "add_scheduled_image",
      description: "Attach an image to a scheduled release order",
      inputSchema: z.object({
        scheduled_order_id: z.number().describe("Scheduled release order ID"),
        url: z.string().describe("Image URL"),
        alt: z.string().optional().describe("Alt text for the image"),
      }),
      handler: async ({ scheduled_order_id, ...rest }: { scheduled_order_id: number } & Record<string, unknown>) =>
        paPost(`/scheduled_release_orders/${scheduled_order_id}/scheduled_release_image.json`, {
          scheduled_release_image: rest,
        }),
    },
    {
      name: "add_scheduled_subject",
      description: "Add a subject/topic to a scheduled release order",
      inputSchema: z.object({
        scheduled_order_id: z.number().describe("Scheduled release order ID"),
        subject: z.string().describe("Subject or topic for releases in this order"),
      }),
      handler: async ({ scheduled_order_id, ...rest }: { scheduled_order_id: number } & Record<string, unknown>) =>
        paPost(`/scheduled_release_orders/${scheduled_order_id}/scheduled_release_subject.json`, {
          scheduled_release_subject: rest,
        }),
    },
    {
      name: "add_scheduled_keyword",
      description: "Add a keyword to a scheduled release order",
      inputSchema: z.object({
        scheduled_order_id: z.number().describe("Scheduled release order ID"),
        keyword: z.string().describe("Keyword to target in releases"),
        url: z.string().optional().describe("URL to link this keyword to"),
      }),
      handler: async ({ scheduled_order_id, ...rest }: { scheduled_order_id: number } & Record<string, unknown>) =>
        paPost(`/scheduled_release_orders/${scheduled_order_id}/scheduled_release_keyword.json`, {
          scheduled_release_keyword: rest,
        }),
    },
    {
      name: "add_first_release_keyword",
      description: "Add a keyword specifically for the first release in a scheduled order",
      inputSchema: z.object({
        scheduled_order_id: z.number().describe("Scheduled release order ID"),
        keyword: z.string().describe("Keyword for the first release"),
        url: z.string().optional().describe("URL to link this keyword to"),
      }),
      handler: async ({ scheduled_order_id, ...rest }: { scheduled_order_id: number } & Record<string, unknown>) =>
        paPost(`/scheduled_release_orders/${scheduled_order_id}/first_release_keyword.json`, {
          first_release_keyword: rest,
        }),
    },
  ];
}
